### ISSUE TITLE
Simulink Containers Limit Question

### ISSUE THREAD

**Issue by guilhermeneves** [microsoft/bonsai-simulink#31]
Hi team,

Does anyone know if there is a limitation of simulink instances to run on Azure/Bonsai?
We have 750 instances limit on Bonsai and set min instance as 100 and max  as 750, but we can only got from 9 to 14 instances running with simulink, if we use a data-driven model we have no issues, but using simulink we are having this issue.

Thanks,
Guilherme Neves

**Comment by davidhcoe** [comment]
Hi @guilhermeneves. Sorry we missed this question. There are no limits placed on the simulator counts because they are using Simulink. However, the platform may request different numbers of simulators based on how fast they are.
